
[pre-commit]
parallel = true

[pre-commit.commands.check]
run = "npx biome check --no-errors-on-unmatched {staged_files}"

[pre-commit.commands.cSpell]
run = "npx cspell --no-progress {staged_files}"
